POST http://localhost:3001/api/clips HTTP/1.1
content-type: application/json

{
    "startTime": "00:25:00",
    "endTime": "00:25:00",
    "title": "Chiggers or Berry Bugs w/ Jeremiah Watkins",
    "datePublished": "05/28/2022",
    "link": "https://www.youtube.com/watch?v=x895I70X9zU",
    "name": "Long Days with Yannis Pappas",
    "guests": [
    "Jeremiah Watkins"
    ],
    "hosts": [
    "Yannis Pappas"
    ],
    "notes": "Jeremiah impersonating New Yorkers"
}